# Generated by Django 3.2.7 on 2021-10-13 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fake',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
