# Generated by Django 3.2.7 on 2021-10-21 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_alter_profile_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_seller',
        ),
    ]
