# Generated by Django 4.0 on 2021-12-28 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_remove_profile_is_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='seller_number_ratings',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Number of ratings given to this user', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='seller_ratings',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, help_text='Sellers ratings', max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='sold_keys',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Number of keys sold by this user', null=True),
        ),
    ]
