# Generated by Django 4.0 on 2021-12-28 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_profile_seller_number_ratings_profile_seller_ratings_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='seller_number_ratings',
            new_name='seller_ratings_count',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='seller_ratings',
        ),
        migrations.AddField(
            model_name='profile',
            name='seller_total_ratings',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
