# Generated by Django 4.0 on 2022-01-06 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_rename_seller_number_ratings_profile_seller_ratings_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='seller_ratings_count',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Number of ratings given to this user'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='seller_total_ratings',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sold_keys',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Number of keys sold by this user'),
        ),
    ]
