# Generated by Django 4.0 on 2022-01-08 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_wishlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='product',
            new_name='products',
        ),
    ]
