# Generated by Django 4.0 on 2022-04-19 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0016_alter_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, db_column='Image', default='/profiles/images/img_default.jpeg', help_text='Select a profile picture', null=True, upload_to='profiles/images/'),
        ),
    ]
