# Generated by Django 3.2.7 on 2021-10-03 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id_user', models.UUIDField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=32)),
                ('surname', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
                ('e_mail', models.EmailField(max_length=254, unique=True)),
                ('pic', models.ImageField(blank=True, default='', upload_to='')),
                ('seller', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Customers',
            },
        ),
    ]
