# Generated by Django 3.2.7 on 2021-10-03 15:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userman', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id_game', models.UUIDField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('category', models.CharField(max_length=32)),
                ('developer', models.CharField(max_length=64)),
                ('publisher', models.CharField(max_length=64)),
                ('publishing_date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('pic', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id_key', models.UUIDField(primary_key=True, serialize=False, unique=True)),
                ('serial_key', models.CharField(max_length=64, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sale', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)])),
                ('sold', models.BooleanField(default=False)),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecommerce.product')),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='userman.customer')),
            ],
            options={
                'verbose_name_plural': 'Keys',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_trans', models.UUIDField(unique=True)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('payment_method', models.CharField(blank=True, choices=[('Visa', 'Visa'), ('MasterCard', 'MasterCard'), ('Maestro', 'MasterCard'), ('PayPal', 'PayPal'), ('PaySafeCard', 'PaySafeCard')], max_length=16, null=True)),
                ('state', models.CharField(choices=[('Success', 'Success'), ('Pending', 'Pending'), ('Failure', 'Failure')], default='Pending', max_length=16)),
                ('key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecommerce.key')),
            ],
            options={
                'verbose_name_plural': 'Transactions',
                'unique_together': {('id_trans', 'key')},
            },
        ),
    ]
