# Generated by Django 3.2.7 on 2021-10-06 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name', 'publishing_date'], 'verbose_name_plural': 'Products'},
        ),
    ]
