# Generated by Django 3.2.7 on 2021-10-06 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_alter_product_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Visa', 'Visa'), ('MasterCard', 'MasterCard'), ('Maestro', 'Maestro'), ('PayPal', 'PayPal'), ('PaySafeCard', 'PaySafeCard')], help_text='Choose the payment method', max_length=16, null=True),
        ),
    ]
