# Generated by Django 3.2.7 on 2021-10-06 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_auto_20211006_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='key',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecommerce.key'),
        ),
    ]
