# Generated by Django 3.2.7 on 2021-10-15 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20211015_1648'),
        ('ecommerce', '0005_alter_transaction_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wish', models.JSONField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.profile')),
            ],
            options={
                'verbose_name_plural': 'Wishlists',
                'ordering': ['user__user__username'],
            },
        ),
    ]
