# Generated by Django 3.2.7 on 2021-10-15 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_wishlist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wishlist',
            options={'verbose_name_plural': 'Wishlists'},
        ),
    ]
