# Generated by Django 3.2.7 on 2021-10-15 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_alter_wishlist_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
