# Generated by Django 3.2.7 on 2021-10-19 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0011_alter_key_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='key',
            options={'ordering': ['product', 'serial_key'], 'verbose_name_plural': 'Keys'},
        ),
    ]
