# Generated by Django 4.0 on 2022-01-06 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('ecommerce', '0013_auto_20211021_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerlibrary',
            name='user',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='wish',
        ),
        migrations.AddField(
            model_name='key',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.user'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wishlist',
            name='product',
            field=models.ManyToManyField(blank=True, to='ecommerce.Product'),
        ),
        migrations.DeleteModel(
            name='Library',
        ),
        migrations.DeleteModel(
            name='SellerLibrary',
        ),
    ]
