# Generated by Django 3.2.1 on 2022-01-06 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0014_key_seller'),
        ('ecommerce', '0014_remove_sellerlibrary_user_remove_wishlist_wish_and_more'),
    ]

    operations = [
    ]
