# Generated by Django 4.0 on 2022-01-06 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0015_merge_20220106_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('VISA', 'Visa'), ('MASTERCARD', 'MasterCard'), ('MAESTRO', 'Maestro'), ('PAYPAL', 'PayPal')], help_text='Choose the payment method', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='state',
            field=models.CharField(choices=[('SUCCESS', 'Success'), ('PENDING', 'Pending'), ('FAILURE', 'Failure')], default='Pending', max_length=16),
        ),
    ]
