# Generated by Django 3.2.1 on 2022-01-21 15:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0026_alter_product_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='sale',
            field=models.IntegerField(blank=True, default=0, help_text='Enter the sale value', validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
