# Generated by Django 4.0 on 2022-04-02 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0029_alter_key_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='key',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
