# Generated by Django 4.0 on 2022-04-05 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0030_key_sale_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=666, max_digits=10),
            preserve_default=False,
        ),
    ]
