# Generated by Django 4.0 on 2022-04-19 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0032_alter_transaction_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pic',
            field=models.ImageField(blank=True, db_column='Image', default='/products/images/img_default.jpeg', help_text='Select a picture for the product', null=True, upload_to='products/images/'),
        ),
    ]
