# Generated by Django 3.2.7 on 2021-10-05 17:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Enter a title for the review', max_length=64, null=True)),
                ('text', models.TextField(blank=True, help_text='Enter your review of the product', null=True)),
                ('rate', models.PositiveIntegerField(help_text='Enter your rate for the product (1-10)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('trans', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecommerce.transaction')),
            ],
            options={
                'verbose_name_plural': 'Reviews',
                'ordering': ['title'],
                'unique_together': {('id', 'trans')},
            },
        ),
    ]
