# Generated by Django 3.2.7 on 2021-10-03 15:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_rev', models.UUIDField(unique=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('rate', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('trans', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecommerce.transaction')),
            ],
            options={
                'verbose_name_plural': 'Reviews',
                'unique_together': {('id_rev', 'trans')},
            },
        ),
    ]
