# Generated by Django 3.2.7 on 2021-10-06 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_alter_transaction_key'),
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['product', 'date'], 'verbose_name_plural': 'Reviews'},
        ),
        migrations.AddField(
            model_name='review',
            name='date',
            field=models.DateField(default='2021-10-06'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecommerce.product'),
        ),
        migrations.AlterField(
            model_name='review',
            name='trans',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecommerce.transaction'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('trans', 'product')},
        ),
    ]
