# Generated by Django 4.0 on 2022-01-06 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('ecommerce', '0016_alter_transaction_payment_method_and_more'),
        ('review', '0003_alter_review_date_alter_review_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='trans',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.transaction'),
            preserve_default=False,
        ),
    ]
